{{- if .Values.nvidia.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedqa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chat-assistance.labels" . | nindent 4 }}
    app: embedqa
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: embedqa
  template:
    metadata:
      labels:
        app: embedqa
        gpu-workload: "true"
        {{- include "chat-assistance.labels" . | nindent 8 }}
    spec:
      {{- include "chat-assistance.nodeSelector" . | nindent 6 }}
      {{- include "chat-assistance.nimAntiAffinity" . | nindent 6 }}
      imagePullSecrets:
        - name: ncr-registry-secret
      containers:
        - name: embedqa
          image: {{ .Values.images.embedqa }}
          ports:
            - containerPort: 8000
          env:
            {{- if .Values.nvidia.embedqaProfile }}
            - name: NIM_MODEL_PROFILE
              value: {{ .Values.nvidia.embedqaProfile | quote }}
            {{- end }}
            - name: NGC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ngc-api-secret
                  key: api-key
            - name: NIM_NGC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ngc-api-secret
                  key: api-key
          resources:
            {{- include "chat-assistance.resources.nvidia" . | nindent 12 }}
          securityContext:
            {{- include "chat-assistance.securityContext" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /v1/health/ready
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /v1/health/live
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: embedqa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "chat-assistance.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: llm
    - port : 80
      targetPort: 8000
      name: http-port
  selector:
    app: embedqa
{{- end }}
